# Required for containerised environments
listen_addresses = '*'

# WAL-G archiving and restore settings
archive_mode = on
archive_timeout = 1h
archive_command = '/usr/local/bin/peg wal-push %p'
restore_command = '/usr/local/bin/peg wal-fetch %f %p'

# Include sideloaded configuration files
include_dir = '/etc/postgresql/postgresql.conf.d'
