# WAL-G archiving and restore settings
# This file is included from postgresql.conf by 90-walg-config.sh

archive_mode = on
archive_timeout = 1h
archive_command = '/usr/local/bin/peg wal-push %p'
restore_command = '/usr/local/bin/peg wal-fetch %f %p'
